master/master/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('master_server/', include('master_server.urls'))
]

master/master_server/urls.py
from django.urls import path
from master_server.views import *

app_name = 'master_server'
urlpatterns = [
    path('check_status/<info_type>/', CheckStatus.as_view()),
    path('get_plan/<job_id>/', GetExecPlan.as_view()),
    path('get_plan/', GetExecPlan.as_view()),
    path('del_plan/', DelExecPlan.as_view()),
    path('start/', ServerStart.as_view()),
    path('add_program/', AddProgramApi.as_view(), name='insert'),
    path('send_plan/', SendExecPlan.as_view()),
    path('program/status/<option>/', ProgramStatusCheck.as_view()),
    path('slave_program_result/', SlaveProgramResult.as_view()),
    path('sync_result/', SyncResult.as_view()),
    path('get_cal_result/<pk>/', GetCalResult.as_view()),
    path('get_cal_result/', GetCalResult.as_view()),
    path('exec_api/<sid>/', ExecApi.as_view()),
]

master/templates/Base.html
{% load menu %}
<!DOCTYPE html>
<!-- saved from url=(0042)https://v3.bootcss.com/examples/dashboard/ -->
<html lang="zh-CN">
<head><meta http-equiv="Content-Type" content="text/html; charset=UTF-8">
    
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <!-- 上述3个meta标签*必须*放在最前面，任何其他内容都*必须*跟随其后！ -->
    <meta name="description" content="">
    <meta name="author" content="">
    <link rel="icon" href="https://v3.bootcss.com/favicon.ico">

    <title>My First website</title>

    <!-- Bootstrap core CSS -->
    <link href="/static/bootstrap/dist/css/bootstrap.css" rel="stylesheet">

    <!-- Custom styles for this template -->
    <link href="/static/css/dashboard.css" rel="stylesheet">

  <link rel="stylesheet" type="text/css" href="chrome-extension://fidicgekecdkdmkjghdgadgdmcfodfid/themes/default/content.css">
<style>
    a {
        cursor: pointer;
    }

</style>
    {% block style %}
    {% endblock %}

</head>

  <body>
  <div class="edit_edit"></div>

    <nav class="navbar navbar-inverse navbar-fixed-top">
      <div class="container-fluid">
        <div class="navbar-header">
          <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#navbar" aria-expanded="false" aria-controls="navbar">
            <span class="sr-only">Toggle navigation</span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
          </button>
          <div class="navbar-brand">Welcome &nbsp;&nbsp;{{ request.user.last_name }}&nbsp;{{ request.user.first_name }}</div>
        </div>

        <div id="navbar" class="navbar-collapse collapse">
          <ul class="nav navbar-nav navbar-right">
              <li><a href="/logout/">Logout</a></li>
          </ul>
            <form class="navbar-form navbar-right">
        <div class="form-group">
          <input type="text" class="form-control" placeholder="Search">
        </div>
        <button type="submit" class="btn btn-default">搜索</button>
      </form>
        </div>
      </div>
    </nav>

    <div class="container-fluid">
      <div class="row">
        <div class="col-sm-3 col-md-1 sidebar">
            <ul class="nav nav-sidebar">
                <li  id=4><a href="{% url 'master_server:insert' %}" >添加执行计划 </a></li>
             </ul>
        </div>

        <div class="col-sm-9 col-sm-offset-3 col-md-10 col-md-offset-1 main">
            {% block container%}
                <div class="jumbotron">
                    <h1>普益脚本管理 version：1.0</h1><br>
                    <p>这是一个用于自动化运维的管理、展示控制台demo</p>
                    <p>Author ：     胡睿智</p>
                </div>
            {% endblock %}
        </div>
      </div>
    </div>

    <!-- Bootstrap core JavaScript
    ================================================== -->
    <!-- Placed at the end of the document so the pages load faster -->
    <script src="/static/jquery-3.2.1.js"></script>
    <script>window.jQuery || document.write('<script src="../../assets/js/vendor/jquery.min.js"><\/script>')</script>
    <script src="/static/bootstrap/dist/js/bootstrap.js"></script>
    <!-- Just to make our placeholder images work. Don't actually copy the next line! -->
    <script src="/static/holder.js"></script>
    <script>
        $(function (){
            $("a[href='{{ request.path }}']").parent().addClass("active")
        });

<!-- csrftoken -->
        function getCookie(name) {
    var cookieValue = null;
    if (document.cookie && document.cookie != '') {
        var cookies = document.cookie.split(';');
        for (var i = 0; i < cookies.length; i++) {
            var cookie = jQuery.trim(cookies[i]);
            // Does this cookie string begin with the name we want?
            if (cookie.substring(0, name.length + 1) == (name + '=')) {
                cookieValue = decodeURIComponent(cookie.substring(name.length + 1));
                break;
            }
        }
    }
    return cookieValue;
}
var csrftoken = getCookie('csrftoken');


function csrfSafeMethod(method) {
    // these HTTP methods do not require CSRF protection
    return (/^(GET|HEAD|OPTIONS|TRACE)$/.test(method));
}
$.ajaxSetup({
    beforeSend: function(xhr, settings) {
        if (!csrfSafeMethod(settings.type) && !this.crossDomain) {
            xhr.setRequestHeader("X-CSRFToken", csrftoken);
        }
    }
});
    </script>

{% block script %}
{% endblock %}
</body></html>