master/master/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('master_server/', include('master_server.urls'))
]

master/master_server/models.py
from django.db import models
# Create your models here.


class ServerInfo(models.Model):
    is_alive = ((1, 'on_line'), (0, 'off_line'))
    ip = models.GenericIPAddressField(protocol='IPv4')
    port = models.IntegerField(default=33541)
    name = models.CharField(max_length=100)
    uptime = models.DateTimeField(auto_now=True)
    status = models.IntegerField(choices=is_alive, default=0)

    def __str__(self):
        return 'IP:%s, Port:%s' % (self.ip, self.port)

    class Meta:
        db_table = 'py_script_server_info_v2'
        app_label = "master_server"


class Path(models.Model):
    server = models.ForeignKey('ServerInfo', on_delete=models.DO_NOTHING)
    path = models.CharField(max_length=200)
    project = models.CharField(verbose_name='项目名称', max_length=50)

    def __str__(self):
        return "project:(%s),[Server:(%s)]Path:%s" % (self.project, self.server, self.path)

    class Meta:
        db_table = 'py_script_programs_path'
        unique_together = ('server', 'path', 'project')
        app_label = "master_server"


class ConfigFileLog(models.Model):
    path = models.ForeignKey('Path', on_delete=models.DO_NOTHING)
    project_conf = models.FileField(upload_to='project_conf/')
    project_package = models.FileField(upload_to='project_package/', blank=True, null=True)
    comments = models.TextField(blank=True, null=True)

    class Meta:
        db_table = 'py_script_config_file_log'
        app_label = "master_server"


class TablesInfo(models.Model):
    db = (('db_ali', 'db_阿里云'), ('db_151', 'db_151'), ('db_153', 'db_153'), ('db_155', 'db_155'))
    source = ((0, '程序产生'), (1, '人工录入'), (2, '其他'))
    db_server = models.CharField(max_length=20, choices=db)
    db_name = models.CharField(max_length=30)
    table_name = models.CharField(max_length=100)
    data_source = models.IntegerField(choices=source, default=0)

    def __str__(self):
        return "%s:%s.%s" % (self.db_server, self.db_name, self.table_name)

    class Meta:
        db_table = 'py_script_tables_info'
        unique_together = ('db_server', 'db_name', 'table_name')
        app_label = "master_server"


class PyScriptBaseInfoV2(models.Model):

    is_stop_choice = ((0, '执行'),
                      (1, '停止'))

    run_type = ((0, '调用api'),
                (1, '调用程序'))

    program_type = ((0, '计划任务'),
                    (1, '计算'),
                    (2, '其他'))

    sid = models.AutoField(primary_key=True)
    name = models.CharField(verbose_name='名称', max_length=500)
    program_type = models.IntegerField(verbose_name='程序类型', choices=program_type)
    version = models.DateField(blank=True, null=True)
    run_type = models.SmallIntegerField(choices=run_type, default=0)
    pre_tables = models.ManyToManyField('TablesInfo', related_name='son_program', blank=True)
    result_tables = models.ManyToManyField('TablesInfo', related_name='father_program')
    path = models.ForeignKey('Path', on_delete=models.CASCADE, related_name='program')
    function = models.TextField(verbose_name='程序功能', max_length=50)
    owner = models.ForeignKey('PyScriptOwnerListV2', on_delete=models.CASCADE, related_name='programs')
    times = models.IntegerField(default=1)
    is_stop = models.IntegerField(default=0, choices=is_stop_choice)
    cron = models.CharField(verbose_name='执行计划', max_length=20, blank=True, null=True)

    def __str__(self):
        return "sid:%s server:%s script_name:%s " % (self.sid, self.path, self.name)

    class Meta:
        db_table = 'py_script_base_info_v2'
        app_label = "master_server"


class PyScriptOwnerListV2(models.Model):
    owner = models.CharField(verbose_name='所有者', max_length=10, primary_key=True)
    mail = models.EmailField()

    def __str__(self):
        return self.owner

    class Meta:
        db_table = 'py_script_owners_info_v2'
        app_label = "master_server"


class ResultLog(models.Model):
    event_type_list = ((0, '执行调度'), (1, '开始执行'), (2, '正常结束'), (3, '异常终止'),)
    script = models.ForeignKey('PyScriptBaseInfoV2', on_delete=models.CASCADE,
                               related_name='result', db_column='sid', null=True)
    version = models.DateField()
    event_time = models.DateTimeField()
    subversion = models.DateTimeField(blank=True, null=True)
    event_type = models.IntegerField(choices=event_type_list)
    extra_info = models.TextField(blank=True, null=True)
    flag = models.IntegerField(blank=True, null=True)

    def __str__(self):
        return "script:{script}, version:{version}".format(script=self.script, version=self.version)

    class Meta:
        db_table = 'py_script_result_log'
        app_label = "master_server"

master/templates/rcrontab_formals/insert.html
{% extends 'Base.html' %}

{% block container %}


     <form  enctype="multipart/form-data" method="post" name="plan_info" id="insert_plan">
			<div class="modal-body">{% csrf_token %}

<table class="table">
    <thead>
    <tr>
        <th>字段</th>
        <th>值</th>
    </tr>
    </thead>
    <tbody>
    {% for item in form %}
        <tr>
        <td>{{ item.label_tag }}</td>
        <td>{{ item }}</td>
        </tr>
    {% endfor %}
    </tbody>
</table>
{% if errs %}
<div class="alert alert-danger alert-dismissible" role="alert">
    <button type="button" class="close" data-dismiss="alert" aria-label="Close"><span aria-hidden="true">&times;</span></button>
        {{ errs }}
</div>
{% endif %}
			</div>
			<div class="modal-footer">
			</div>
            </form>
                <button type="button" class="btn btn-primary" onclick="submit_data()" data-toggle="modal" data-target="#myModal">
					提交
				</button>


    <!-- Modal -->
<div class="modal fade" id="myModal" tabindex="-1" role="dialog" aria-labelledby="myModalLabel">
  <div class="modal-dialog" role="document">
    <div class="modal-content">
      <div class="modal-header">
        <button type="button" class="close" data-dismiss="modal" aria-label="Close"><span aria-hidden="true">&times;</span></button>
        <h4 class="modal-title" id="myModalLabel">提交执行计划</h4>
      </div>
      <div class="modal-body">
        <div class="progress">
        <div class="progress-bar progress-bar-striped active" role="progressbar" aria-valuenow="45" aria-valuemin="0" aria-valuemax="100" style="width: 0%"><span class="sr-only">0%</span>
        </div>
        </div>
          <div id="in_modal">

          </div>
      </div>
    </div>
  </div>
</div>

{% endblock %}

{% block script %}
    <script>
function onprogress(evt){
　　var loaded = evt.loaded;     //已经上传大小情况
 var tot = evt.total;      //附件总大小
 var per = Math.floor(100*loaded/tot);  //已经上传的百分比
　　$(".progress-bar").css('width',per+"%")
    $(".progress-bar").text(per)

}

function submit_data() {
    var form_data = new FormData();
    form_data.append('path', $('#id_path').val());
    form_data.append('project_conf', $('#id_project_conf')[0].files[0]);
    form_data.append('project_package', $('#id_project_package')[0].files[0]);
    form_data.append('comments', $('#id_comments').val());
    $(".progress-bar").css('width',"0%")
    $(".progress-bar").text(0)
            $.ajax({
                type:"post",
                url: "{{ request.path }}",
                data: form_data,
                contentType:false,
                processData:false,

                //这里我们先拿到jQuery产生的 XMLHttpRequest对象，为其增加 progress 事件绑定
                xhr: function(){
　　　　　　    var xhr = $.ajaxSettings.xhr();
　　　　　　    if(onprogress && xhr.upload) {
　　　　　　　　xhr.upload.addEventListener("progress" , onprogress, false);
　　　　　　　　return xhr;}
　　　　        },
                success:function (arg) {
                    $("#in_modal").empty()
                    $("#in_modal").append(arg)
            }
    });
}


</script>
{% endblock %}